# Generated by Django 3.2.5 on 2021-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20210901_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
