# Generated by Django 3.2.8 on 2021-10-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Member', 'Member')], max_length=50, null=True),
        ),
    ]
